version: "3"
services:
        redis-server:
                image: "redis"
                restart: always
        back_end:
                restart: always
                build: .
                ports:
                        - "4001:8081"
